CREATE DATABASE mydb;

USE mydb
CREATE TABLE MY_TABLE (
    id INT PRIMARY KEY, name VARCHAR(20)
);
INSERT INTO MY_TABLE VALUES (1, 'JH');
INSERT INTO MY_TABLE VALUES (2, 'SH');
INSERT INTO MY_TABLE VALUES (3, 'DE');