version: '3.7'
services:
  prometheus:
    image: prom/prometheus:v2.16.0
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml  # prometheus config volume
    ports:
      - "9090:9090"
    expose:
      - "9090"

  discovery:
    build: discovery
    environment:
      - java.security.egd=file:/dev/./urandom
      - "SPRING_PROFILES_ACTIVE=local"
    ports:
      - "23001:23001"
    expose:
      - "23001"

  product:
    build: product
    environment:
      - "java.security.egd=file:/dev/./urandom"
      - "server.contextPath=/product"
      - "spring.profiles.active=local"
    ports:
      - "24002:24002"
    expose:
      - "24002"
    depends_on:
      - discovery

  display:
    build: display
    environment:
      - java.security.egd=file:/dev/./urandom
      - server.contextPath=/display
      - "SPRING_PROFILES_ACTIVE=local"
    ports:
      - "24001:24001"
    expose:
      - "24001"
    depends_on:
      - discovery