version: '3.7'
services:
#  elk:
#    image: sebp/elk:671
#    container_name: elk
#    ports:
#      - "5601:5601"   # kibana
#      - "9200:9200"   # es
#      - "5044:5044"   # logstash
#    environment:
#      - ES_JAVA_OPTS=-Xms1g -Xmx2g
#      - ES_CONNECT_RETRY=50

#  zipkin:
#    image: openzipkin/zipkin
#    container_name: zipkin
#    environment:
#      - STORAGE_TYPE=elasticsearch
#      - ES_HOSTS=elk:9200
#    ports:
#      - "9411:9411"
#    depends_on:
#      - elk

  maria:
    image: mariadb:10.1.30
    container_name: "mariadb"
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
#      - ./mariadb/data:/var/lib/mysql
      - ./mariadb/my.cnf:/etc/mysql/my.cnf
      - ./mariadb/init:/docker-entrypoint-initdb.d/:ro
    environment:
      - MYSQL_ROOT_PASSWORD=jinhyun
      - TZ="Asia/Seoul"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  prometheus:
    image: prom/prometheus:v2.5.0
    container_name: "prom"
    environment:
      - storage.tsdb.path=/prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml  # prometheus config volume
      - ./prometheus/alert.rules.yml:/etc/prometheus/alert.rules.yml  # alert.rules volume
#      - /prometheus-tsdb:/prometheus
    ports:
      - "9090:9090"
    expose:
      - "9090"
    depends_on:
      - discovery

  alertmanager:
    container_name: "alertmanager"
    image: "prom/alertmanager"
    ports:
      - "9093:9093"
    expose:
      - "9093"

  grafana:
    image: grafana/grafana:latest
    container_name: "grafana"
    ports:
      - "3000:3000"
    expose:
      - "3000"

  discovery:
    build: discovery
    container_name: "eureka"
    environment:
      - java.security.egd=file:/dev/./urandom
      - server.contextPath=/discovery
      - spring.profiles.active=local
    ports:
      - "23001:23001"
    expose:
      - "23001"

  product:
    build: product
    container_name: "sv-prd"
    stdin_open: true
    tty: true
    environment:
      - java.security.egd=file:/dev/./urandom
      - server.contextPath=/product
      - spring.profiles.active=local
    ports:
      - "24002:24002"
    expose:
      - "24002"
    depends_on:
      - discovery

  display:
    build: display
    container_name: "sv-display"
    environment:
      - java.security.egd=file:/dev/./urandom
      - server.contextPath=/display
      - spring.profiles.active=local
    ports:
      - "24001:24001"
    expose:
      - "24001"
    depends_on:
      - discovery