server:
  port: 24002

spring:
  application:
    name: product

eureka:
  instance:
    hostname: localhost
    lease-expiration-duration-in-seconds: 5
    lease-renewal-interval-in-seconds: 5
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery:23001/eureka/
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
