groups:
  - name: Discovery alerts
    rules:
      - alert: Discovery down
        expr: up{job="discovery-metrics"} == 0
        for: 10s
        labels:
          severity: warning
        annotations:
          title: Node {{ $labels.instance }} is down
          description: Failed to scrape {{ $labels.job }} on {{ $labels.instance }} for more than 3 minutes. seems down.