server:
  port: 8081

spring:
  application:
    name: display

# 타임아웃 조건
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000
      circuitBreaker:
        requestVolumeThreshold: 1 #default 20
        errorThresholdPercentage: 50  #default 50
        sleepWindowInMilliseconds: 10000 #default 5000